/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JniTest1 */

#ifndef _Included_JniTest1
#define _Included_JniTest1
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JniTest1
 * Method:    testCode
 * Signature: ([IJJJ)J
 */
JNIEXPORT jlong JNICALL Java_JniTest1_testCode
  (JNIEnv *, jclass, jintArray, jlong, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
